### ISSUE TITLE
Plugin version of the recorder

### ISSUE THREAD

**Issue by UltraHispeed-Elite** [Bryan1029384756/PaperRecorder#10]
### Is your feature request related to a problem?

no, more if there's an alternative or something.

### Describe the solution you'd like.

I'm using a specific fork of PaperMc, and was wondering if there is a plugin version of this I could use on my server.

### Describe alternatives you've considered.

none

### Other

great server software btw!!!

**Comment by Moyettes** [comment]
The only other alternative of this is the fabric version, I currently have no plans to port this to a plugin. I'm currently updating to the newest version here but i have been busy and still need to finish with the new packet changes

**Comment by UltraHispeed-Elite** [comment]
then how would you recommend going about implementing the mod into a fork of paper? (and I mean a fork of paper, not folia)

**Comment by Moyettes** [comment]
There currently is no way. The only two projects that do this is this fork and the mod. Both won't work with another fork of paper. It can be built on top of the other fork. So let's say for example you are using Purpur or Pufferfish you would make a new patch containing the changes I made into their fork and make a custom jar. Having the benefits of that fork with this fork. Doing this takes some understanding of Java and if you are using a newer version 1.20.2+ you would need to finish the packet changes to make it work in the newest versions of Minecraft

**Comment by UltraHispeed-Elite** [comment]
ah ok, it was worth a shot, I've been torn between using this server software and Multi-paper's server software, and was hoping for a way to use both the replay ability and multiple servers under a host server, but Thanks anyways for the info, I might just go with this server because it's a great way to prevent my friends from cheating a getting away with it again lol
