### ISSUE TITLE
是否能帮助更新fabric mod1.21版本

### ISSUE THREAD

**Issue by Adogs1** [Bryan1029384756/PaperRecorder#11]
### Is your feature request related to a problem?

原作者的fabric库改为只读，我现在需要1.21fabric版本的mod，迫不得已，我只能寻找fork了原作者的开发者寻求帮助！

### Describe the solution you'd like.

如上

### Describe alternatives you've considered.

如上

**Comment by Moyettes** [comment]
I haven't had time to update this. You probably talking about the server side replay mod went to read only but this is a paper fork. If you need a alternative I recommend https://github.com/senseiwells/ServerReplay for a fabric mod. It's up to date.

**Comment by Adogs1** [comment]
> 我没有时间更新这个。您可能正在谈论服务器端重播模组，但这是一个纸叉。如果您需要替代方案，我建议[您 https://github.com/senseiwells/ServerReplay](https://github.com/senseiwells/ServerReplay) 使用织物模组。它是最新的。

谢谢你的推荐，总算有了进展！
