### ISSUE TITLE
Missing plugin.yml

### ISSUE THREAD

**Issue by StayCh1ll** [Bryan1029384756/PaperRecorder#7]
### Expected behavior

The plugin loading normally.

### Observed/Actual behavior

Plugin failed to load due to: 
`java.lang.IllegalArgumentException: Directory 'plugins/paperrecord-bundler-1.20.1-R0.1-SNAPSHOT-reobf.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!`

### Steps/models to reproduce

N/A

### Plugin and Datapack List

Plugins:

- worldedit-bukkit-7.2.15
- WorldEditSelectionVisualizer-2.1.4
- worldguard-bukkit-7.0.9-beta1
- paperrecord-bundler-1.20.1-R0.1-SNAPSHOT-reobf

Datapacks:

- Vanilla Tweaks: cauldron concrete v2.0.7 (MC 1.20.x)

### Folia version

N/A

### Other

Upon opening the jar file with WinRAR, the plugin.yml file is in fact missing. The file was not modified in any way before being uploaded to my server.

**Comment by Moyettes** [comment]
This is **NOT** a plugin this replaces the Server jar file. If you are running paper this replaces your paper.jar file. If you are running Paper, Spigot, Purpur or any other software this will replace it. It is build ontop of paper and will work with all Bukkit plugins.
